name: Test Playwright with Allure report

on:
  push:
    branches: [ main ]

jobs:

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - name: Start testing
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm ci
    - run: npx playwright install
    - run: npm test

    - uses: actions/upload-artifact@main
      with:
        name: allure-results
        path: allure-results
        retention-days: 2

    - name: Get Allure history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Test marketplace action
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history     